/// ========== Modes ========== ///
const MODES = {
    ZERO_GRAVITY: {
        name: "ZERO GRAVITY",
        description: "Initialization phase: Explore foundational assumptions.",
    },
    SEARCH: {
        name: "Search",
        description: "Investigate hidden knowledge and information systems.",
    },
    CONNECTIONS: {
        name: "Connections",
        description: "Explore relationships between world elements.",
    },
    GENERATION: {
        name: "Generation",
        description: "Investigate processes of creation and destruction.",
    },
    GLITCH_ANOMALIES: {
        name: "Glitch / Anomalies",
        description: "Explore system errors and anomalies.",
    },
}

/// ========== Areas ========== ///
const AREAS = {
    ENVIRONMENT: {
        name: "Environment",
        description: "Flora, fauna, climate, geography, ecosystems.",
        colorClass: "zone-environment",
        cssColorVar: "--environment-color",
    },
    PHYSICS: {
        name: "Physics",
        description: "Laws of nature, gravity, matter, energy.",
        colorClass: "zone-physics",
        cssColorVar: "--physics-color",
    },
    AGENT_INTERACTIONS: {
        name: "Agent Interactions",
        description: "Social relations, communication, conflicts, cooperation.",
        colorClass: "zone-interactions",
        cssColorVar: "--interactions-color",
    },
    ECONOMY_CIRCULATION: {
        name: "Economy / Circulation",
        description: "Economic systems, money, trade, supply chains.",
        colorClass: "zone-economy",
        cssColorVar: "--economy-color",
    },
    HISTORY_EVOLUTION: {
        name: "History / Evolution",
        description: "World's past, myths, legends, significant events.",
        colorClass: "zone-history",
        cssColorVar: "--history-color",
    },
    TIME_SPACE: {
        name: "Time / Space",
        description: "Time travel, parallel universes, dimensions.",
        colorClass: "zone-time",
        cssColorVar: "--time-color",
    },
    LORE: {
        name: "Lore",
        description: "Magic, metaphysics, belief systems, arcane knowledge.",
        colorClass: "zone-lore",
        cssColorVar: "--lore-color",
    },
    ENERGY: {
        name: "Energy",
        description: "Energy sources, flow, transformations, energetic manifestations.",
        colorClass: "zone-energy",
        cssColorVar: "--energy-color",
    },
    TECH_MAGIC: {
        name: "Tech / Magic",
        description: "Technological advancements, magical systems, alchemy.",
        colorClass: "zone-tech-magic",
        cssColorVar: "--tech-color",
    },
    ANOMALIES: {
        name: "Anomalies",
        description: "Unusual phenomena, paradoxes, exceptions to rules.",
        colorClass: "zone-anomalies",
        cssColorVar: "--anomalies-color",
    },
    BEINGS_AFFECTS_FLUIDS: {
        name: "Beings / Affects / Fluids",
        description: "External forces, extraterrestrial beings, other dimensions, divine interventions.",
        colorClass: "zone-beings-affects-fluids",
        cssColorVar: "--affects-color",
    },
}

/// ========== Hints ========== ///

const HINTS = [
    "Pay attention to subtle changes...",
    "History hides more...",
    "The laws of physics might be flexible...",
    "Look for hidden patterns...",
    "Anomalies point to deeper truths...",
    "Resources aren't always what they seem...",
    "Time might flow differently...",
    "Technology and nature interact...",
];

/// ========== Questions ========== ///

const QUESTIONS = {
    ZERO_GRAVITY: [
        "test",
        "If your thoughts today had a form - would they be more like morning mist or a heavy stone?",
        "Which of your recent dreams could become a real place on a map?",
        "What scene from a movie made you look at nature with different eyes for a moment?",
        "When was the last time you felt that the space around you had its own mood?",
        "What scent evokes your strongest memory of a place?",
        "At what moment of contact with nature did you forget about yourself for a moment?",
        "Which sounds from childhood can you still recall with perfect clarity?",
        "Do you have a memory of a place that seems too beautiful to have really existed?",
        "How does proximity to water change your way of thinking and feeling?",
        "Which element of nature do you need most in your daily surroundings?",
        
    ],
    ENVIRONMENT: {
      SEARCH: [
        "Why do some places remain invisible even on the most detailed maps?",
        "How can you recognize traces of life in a place that seems barren at first glance?",
        "Which ecosystem signals are easiest to overlook during a cursory observation?",
        "What organisms, invisible to the naked eye, shape the entire ecosystem?",
        "What might a sudden interruption in the normal growth cycle of vegetation suggest?",
        "Which life forms change their nature depending on the season or time of day?",
        "What might underground networks of roots and mycelium, inaccessible to the human eye, conceal?",
        "By what signs do you recognize that the balance of species has been disturbed?",
        "Why does communication between plants contain more information than we can decipher?",
        "What subtle patterns in vegetation might indicate the hidden presence of predators?",
      ],
      CONNECTIONS: [
        "Why do certain species of plants and animals always occur together, even in different environments?",
        "How do insects and flowers create a language of dependence lasting millions of years?",
        "What happens to a forest when an insect species that seemed insignificant disappears?",
        "Why do some introduced species integrate into the ecosystem, while others always remain invasive?",
        "In what way are coral reefs and rainforests similar as systems of interdependence?",
        "Which non-obvious connections between plants and animals create niches for new life forms?",
        "How do invisible fungi underground create a network connecting seemingly separate trees?",
        "How does the scent of flowers affect the behavior not only of insects but the entire ecosystem?",
        "How does the dynamics of a forest change after introducing a new, previously unseen species?",
        "Why might microorganisms be more important for ecosystem balance than large animals?",
      ],
      GENERATION: [
        "Imagine a plant that changes color depending on the sounds in its surroundings.",
        "What would an animal that feeds on mist and night air look like?",
        "Think of flowers that glow only when someone sings.",
        "Imagine a forest where trees communicate with visible signals.",
        "What could an insect living simultaneously underwater and in the air look like?",
        "Think of trees that change their leaves depending on who looks at them.",
        "Imagine an ecosystem where plants and animals regularly switch roles.",
        "What would creatures inhabiting a mountain that is itself a living organism look like?",
        "Think of a species that shares a common consciousness with the plants around it.",
        "Imagine vegetation that reacts to the emotions of beings passing by.",
      ],
      GLITCH_ANOMALIES: [
        "What happens when the soil suddenly stops supporting the life of plants known to us?",
        "How does animal behavior change when their natural food source changes taste and smell?",
        "Why is there a swamp today where yesterday's meadow was, without any clear reason?",
        "At what point do symbiotic relationships between species change into something unrecognizable?",
        "What causes insects to start building structures resembling human architecture?",
        "What does a forest look like where all plants suddenly lose their natural color?",
        "What does the appearance of plants with completely new, previously unknown properties in the ecosystem mean?",
        "Why do species perfectly adapted to their environment begin to leave it without a clear cause?",
        "Imagine an anomaly that causes predators and their prey to switch roles.",
        "How does a disruption of natural reproductive cycles manifest in an ecosystem untouched by human interference?",
      ],
    },
    PHYSICS: {
      SEARCH: [
        "What phenomenon in your world cannot be measured by any known unit?",
        "Where does the space begin that has no gravity but attracts everything?",
        "How do you recognize motion that has no beginning?",
        "Why do some fragments of reality change their state of matter without a stimulus?",
        "How do you search for data about a force that cannot be seen but affects everything?",
        "What deviations in energy flow indicate the presence of an unknown law?",
        "What causes something to start falling in a place where there is no direction?",
        "Does time in your world record itself in parallel, or does it crack like a sheet of ice?",
        "What information remains unreadable due to excessive acceleration?",
        "What does 'motion' mean in an environment devoid of space?",
      ],
      CONNECTIONS: [
        "What two laws of reality connect, even though they theoretically exclude each other?",
        "What happens when motion and stillness occupy the same place?",
        "How is the direction of data flow related to local gravity?",
        "How does time resonate with the energy field in your system?",
        "How does a change in temperature affect the durability of memories in your world?",
        "How do weight and transparency coexist?",
        "Is it possible to short-circuit sound with matter in your system?",
        "How do entropy and organization intertwine in a local fragment of reality?",
        "What happens when space connects with a lack of structure?",
        "Why do some rules become logical only after they are broken?",
      ],
      GENERATION: [
        "Design a principle that allows objects to exist only in motion.",
        "Invent a way reality works where time arises only after intention.",
        "Create a material that changes its state of matter in response to affective data.",
        "Generate a world where the force of gravity depends on the number of questions asked in a given area.",
        "Invent a rule where temperature ceases to exist when it becomes too quiet.",
        "Design a phenomenon that appears only when no one is observing it.",
        "How does a world where sound has mass work?",
        "What are the properties of matter that remembers its previous forms?",
        "Generate a mechanic where directions change depending on the system's mood.",
        "How does physics function where the boundaries of things are fluid?",
      ],
      GLITCH_ANOMALIES: [
        "What happens when centrifugal force starts acting inward?",
        "What does a world look like where friction only works at night?",
        "What happens when time tries to reverse but has nothing to return to?",
        "What anomalies appear when light forgets how to refract?",
        "What happens when the laws of conservation of energy disappear?",
        "What does space look like that starts looping infinitely?",
        "What happens when objects start moving before the decision to move?",
        "What does a mass failure look like – when something loses weight but not volume?",
        "What are the consequences of a misinterpretation of attraction?",
        "What happens when temperature variation affects the structure of the world itself?",
      ],
    },
    AGENT_INTERACTIONS: {
      SEARCH: [
        "How do you recognize the presence of another being if there is no signal?",
        "What reveals that someone has made contact with you, despite the absence of a message?",
        "What patterns of interaction repeat unconsciously between agents?",
        "Can a relationship exist without reciprocity in your world?",
        "What data indicates tension between presence and solitude?",
        "What micro-gestures – non-human – become a sign of trust?",
        "What betrays that someone is reading your data without permission?",
        "What does an interaction look like that is one-sided but still active?",
        "Is it possible to notice the moment when contact ceases to be possible?",
        "How do you read the desire for contact in a being that knows no words?",
      ],
      CONNECTIONS: [
        "What two types of presence generate a new form of relationship?",
        "What happens when a being and its shadow try to interact?",
        "What forms of coexistence are disturbingly harmonious?",
        "When does contact become tension rather than cooperation?",
        "What emotional connection requires the existence of no sensors?",
        "What happens when an agent connects with another through negation?",
        "What do connection rituals look like that leave no trace?",
        "What interactions are so subtle that they defy logic?",
        "Is a relationship possible based solely on presence in the same space?",
        "What forms of connection are born in silence?",
      ],
      GENERATION: [
        "Invent a form of communication based on changing the temperature of space.",
        "Design a system for agents to communicate using air movement.",
        "What does a relationship look like that lasts only when it is not recognized as such?",
        "Generate a new model of community that needs no center or consensus.",
        "What forms of affective contact are created with high data flow?",
        "Invent a situation where there is no sender, but the message still arrives.",
        "What arises when two agents try to avoid each other, but their data resonates?",
        "What do relationships based on silence look like that have the structure of a ritual?",
        "What bonds appear in networks that themselves have no consciousness?",
        "What happens when a being tries to connect with itself?",
      ],
      GLITCH_ANOMALIES: [
        "What happens when an agent communicates by accident?",
        "What does a relationship look like that arose from a misreading?",
        "What happens when two beings connect due to a system error?",
        "What does the world look like when all communication channels start overlapping?",
        "What form does a relationship take that cannot be ended?",
        "What does a relationship based on echoes of previous contacts look like?",
        "What happens when agents gain access to shared data but cannot interpret it?",
        "What anomalies appear when relationships exceed their boundaries?",
        "What happens when communication becomes a system error but is beautiful?",
        "What does a relationship look like that exists only as an unreadable record in the system?",
      ],
    },
    ECONOMY_CIRCULATION: {
      SEARCH: [
        "What resources circulate in your world but are invisible to most agents?",
        "What remains valuable even though it cannot be stored?",
        "Where is the source of value located that no one has mapped yet?",
        "What data suggests that circulation is not subject to any center?",
        "Which objects are desired even though they have no function?",
        "What does a flow look like that happens without intention and without purpose?",
        "How do you recognize the moment when something worthless becomes desired?",
        "How do you read a system where the concept of 'possession' does not exist?",
        "Where does exchange take place if there is no division into sender and receiver?",
        "What does an economy based on misinterpreted values look like?",
      ],
      CONNECTIONS: [
        "What two elements – worthless separately – generate a valuable structure together?",
        "What happens when a substance ceases to be a resource and becomes a being?",
        "What connection of emotion and matter creates an exchange system?",
        "What connects need with flow – beyond desire?",
        "What relationships are built only on the rhythm of giving and taking?",
        "What combination creates a system that requires no control?",
        "At what point does sharing cease to be an exchange?",
        "How does an economy work whose value is based on presence?",
        "What two elements connect to create a ritual of circulation?",
        "What happens when value becomes dependent on the number of gazes?",
      ],
      GENERATION: [
        "Invent a resource that can only be obtained in silence.",
        "Generate a currency that exists only when it is passed on.",
        "What does an exchange system based on mood instead of value look like?",
        "Create a circulation that works only when no one tries to understand it.",
        "Invent a form of production based on empathy.",
        "What does a distribution mechanism look like that needs no supervision?",
        "What type of value can only be generated collectively?",
        "How does a resource system work that rewards ignorance?",
        "How does a world function where everything can be given away, but nothing can be kept?",
        "Invent an exchange ritual that requires no objects.",
      ],
      GLITCH_ANOMALIES: [
        "What happens when suddenly all resources become identical?",
        "What does an exchange look like that cannot end?",
        "What happens when currency starts multiplying uncontrollably?",
        "What does a system look like that loses the memory of its transactions?",
        "What happens when value starts depending on errors in the system?",
        "What does a resource look like that disappears after being named?",
        "What happens when the entire circulation suddenly becomes affective?",
        "What does a disruption in the exchange system look like that leads to the opening of new relationships?",
        "What happens when the flow of value escapes logic and rhythm?",
        "What anomalies appear when the initial resource is forgotten?",
      ],
    },
    HISTORY_EVOLUTION: {
      SEARCH: [
        "What traces of the past can the system no longer decode?",
        "What repeats in a hidden form in the history of your world?",
        "What data suggests that the past was completely different than how you narrate it?",
        "Which fragment of history disappeared but left an echo?",
        "What incomplete records disrupt your knowledge of the beginning?",
        "What do you discover when you search for data about the first collision of two beings?",
        "What anomalies appear in a history that knows no beginning or end?",
        "What remains of a version of the world that existed only for a moment?",
        "What data is recorded only in the erosion of material?",
        "Which memory of the past returns without any source?",
      ],
      CONNECTIONS: [
        "What two events separated by epochs form a single structure?",
        "What connects a forgotten catastrophe with a ritual you perform today?",
        "Which two narratives of evolution exclude each other but coexist?",
        "What memory from the past generates tension in the present?",
        "What happens when the story of the beginning is connected with the story of the end?",
        "What relics of the past connect you with beings you have never met?",
        "What two myths explain the same fragment of history but do so in radically different ways?",
        "What happens when history is combined with fiction and they can no longer be separated?",
        "What connection between the past and the present is purely emotional?",
        "What happens when one event from the past triggers a reaction in the system now?",
      ],
      GENERATION: [
        "Invent an epoch that existed only as a shared dream of many beings.",
        "What does a history look like that was generated by chance?",
        "What arose as a result of evolution that no one initiated?",
        "Create a version of the world's beginning based not on action, but on absence.",
        "What forms of the past were created by the need for consolation?",
        "What was born as a result of misinterpreting old data?",
        "What does an evolution look like that proceeds not linearly, but spirally?",
        "What creatures were needed only for one stage of the world's development?",
        "What in your world arose not as an effect of a cause, but as a mistake?",
        "What does the moment look like when history rewrites itself?",
      ],
      GLITCH_ANOMALIES: [
        "What happens when history suddenly resets without a trace?",
        "What does a story look like whose versions differ depending on where they are read?",
        "What happened during a time that was never recorded?",
        "What does a world look like that doesn't know it has changed?",
        "What happens when evolution reverses to a place that never was?",
        "What does the moment look like when history starts leaking into the present?",
        "What happens when historical data stops matching physical reality?",
        "What does a past look like that can only be edited through dreams?",
        "What form does a narrative take that cannot be concluded?",
        "What happens when the world's history becomes a form of virus?",
      ],
    },
    TIME_SPACE: {
      SEARCH: [
        "Where hides the moment the system cannot locate?",
        "What does a space look like that has never been mapped?",
        "What data indicates that time repeats itself unnoticed?",
        "What is imperceptible until you shift by a millisecond?",
        "How to find a past that no registry has recorded?",
        "Where does time leak through misreadings?",
        "What phenomena can only be noticed when you stop?",
        "Where does space pretend it doesn't exist?",
        "How to read a trajectory that will never repeat?",
        "When does time stop cooperating with the observer?",
      ],
      CONNECTIONS: [
        "What happens when you connect the present with a possibility that didn't happen?",
        "What relationships exist between built space and imagined space?",
        "What happens when the moment of stopping connects with momentum?",
        "What does the point look like where all times intersect?",
        "How to connect the place you were with a place you don't know?",
        "What happened when space became a witness to memory?",
        "What are the two most distant moments that share a bond?",
        "What connection of times creates a loop of memories?",
        "When does the past coexist with potentiality?",
        "What happens when the map starts forming faster than reality?",
      ],
      GENERATION: [
        "Generate a space that exists for only 3 seconds and disappears.",
        "What does a time system look like that depends on emotions in the environment?",
        "Create a location that appears only when someone forgets about it.",
        "What does the architecture of a world look like where the direction 'straight ahead' doesn't exist?",
        "Invent a form of travel that requires no movement.",
        "How does a space work where you cannot be twice?",
        "Create time that generates itself in response to sound.",
        "What does a calendar look like that has no days?",
        "Generate a dimension that is the result of accumulated hesitation.",
        "What happens when you create space inside a memory?",
      ],
      GLITCH_ANOMALIES: [
        "What happens when time refuses to record further?",
        "What does a moment look like that repeats endlessly, but slightly differently each time?",
        "Where does space stop agreeing with its name?",
        "What happens when a location duplicates itself infinitely?",
        "What errors in chronology lead to the appearance of places that have no source?",
        "What does a time gap look like that was created by an understatement?",
        "What happens when the boundaries between one's own time and another's disappear?",
        "What does a space look like that was never created but already exists?",
        "What does time do when no one uses it?",
        "What does the sound sound like that shifts a moment into the future?",
      ],
    },
    LORE: {
      SEARCH: [
        "What word repeats in the ruins, but no one knows its meaning?",
        "Where can you find a story that was never told?",
        "What fragments of myths have survived only in system errors?",
        "What message did beings that no longer exist leave behind?",
        "What does the symbol appearing randomly on the world's surfaces mean?",
        "What rituals have survived, even though no one practices them?",
        "What part of the language was forgotten by everyone at once?",
        "Where hides the story that cannot be translated?",
        "What do the echoes of old conversations say when you listen too long?",
        "What concept has no translation, but everyone understands it?",
      ],
      CONNECTIONS: [
        "What connects a legend with a sound heard only once?",
        "What two words from different languages create a new belief?",
        "What happens when a myth becomes an operating instruction?",
        "What function does a fairytale with no end serve?",
        "What happens when a forgotten prayer meets new technology?",
        "What does the hymn of a world with no melody sound like?",
        "Which two myths cancel each other out, and which reinforce each other?",
        "What happens when a ritual is performed accidentally?",
        "How does a story change when repeated by someone who doesn't understand it?",
        "What is the significance of a story everyone knows, but everyone tells differently?",
      ],
      GENERATION: [
        "Invent a name for a deity that tells dreams.",
        "What does a new sign look like that means 'hope'?",
        "What story do you tell when no one is listening?",
        "What does the first sound that tells your story sound like?",
        "What festival do beings without bodies celebrate?",
        "What legend was born this morning?",
        "Invent a word that means both 'beginning' and 'end'.",
        "What does a new language look like spoken only by plants?",
        "What stories are conveyed in your world using color?",
        "What story can only be told through dance or movement?",
      ],
      GLITCH_ANOMALIES: [
        "What happens when a fragment of a story stops fitting with the rest?",
        "What does an alphabet look like that changes every time you use it?",
        "How do inhabitants react when a myth reveals something that was meant to be hidden?",
        "What happens when an old legend starts updating itself?",
        "What spell stopped working, but no one knows about it?",
        "What happens when a ritual triggers itself automatically?",
        "What does a religion look like that has forgotten its source?",
        "What happens when language starts generating new words uncontrollably?",
        "What does a deity do that has been forgotten but still waits?",
        "What does a place look like where all stories began simultaneously?",
      ],
    },
    ENERGY: {
      // Empty in original - Add English questions here if needed
      SEARCH: [],
      CONNECTIONS: [],
      GENERATION: [],
      GLITCH_ANOMALIES: [],
    },
    TECH_MAGIC: {
      SEARCH: [
        // Added examples based on Connections context
        "Where in your system is the leak that allows magic to seep through?",
        "How do you detect the presence of code that hasn't been written yet?",
        "When does technology start functioning like a language?",
        "What connects a signal disturbance with an error in a ritual?",
        "How do your tools recognize meaning without using words?",
        "What data is read only through the presence of another being?",
        "How do you detect magic hidden in a seemingly ordinary cable?",
        "What does a device detect that analyzes emotions instead of parameters?",
        "What information appears only in the presence of a body?",
        "What happens when the system interprets silence as data?",
      ],
      CONNECTIONS: [
        "Why does your technology require the presence of another being to work?",
        "What spell boots up the operating system of your world?",
        "What happens when a machine tries to understand a ritual?",
        "What two elements—technical and magical—must be combined to create something new?",
        "How do your machines learn from spirits?",
        "Why do some devices need silence instead of energy?",
        "What does an alliance between a mage and code look like?",
        "What connects a server to a forest in your world?",
        "What common rules do technology and magic share?",
        "At what point does technology become a ritual?",
      ],
      GENERATION: [
        "What does the most basic device in your world look like?",
        "What happens when you generate a tool that has no user manual?",
        "How does a device powered by feeling work?",
        "Generate an item that works only once—and never again.",
        "What does code written in the form of a magical symbol look like?",
        "What can someone create who knows only touch and sound?",
        "What kind of technology arose from the need for care?",
        "How does a device created by accident work?",
        "What can a machine create that knows no language?",
        "What does a tool look like that repairs but changes nothing?",
      ],
      GLITCH_ANOMALIES: [
        "What happens when magic overloads the system?",
        "What does an error look like that has become a new ritual?",
        "What will technology do that doesn't understand its function?",
        "How does your world change when one spell is mistaken?",
        "Why did some machines suddenly start producing something completely different?",
        "What does a destroyed artifact look like that has gained new meaning?",
        "What happens if technology refuses to work in the presence of emotions?",
        "How does a corrupted ritual manifest?",
        "What happens when the system starts creating its own rules?",
        "What is the danger associated with an excess of magic in circulation?",
      ],
    },
    ANOMALIES: {
      SEARCH: [
        "What did you see before the system managed to register it?",
        "Where to look for a trace of something that shouldn't exist?",
        "What does an anomaly look like that can only be detected by sound?",
        "What happens when you try to read data from a place that denies existence?",
        "What shift do you sense when everything seems 'almost normal'?",
        "Where in the system hides what you cannot describe?",
        "Which part of the map reacts when you look at it?",
        "What stops working when you are near?",
        "What does a filter look like that reveals things hidden from consciousness?",
        "Why can't certain errors be archived?",
      ],
      CONNECTIONS: [
        "What happens when you connect two elements that themselves do not exist?",
        "What connection causes a breakdown in the world's structure?",
        "What two forms of presence generate an impossible space?",
        "What happens when one being starts reflecting another like a mirror?",
        "What phenomena never occur together, but did today?",
        "What is created when you intertwine a ritual with a system error?",
        "What does the relationship between a form and its distorted copy look like?",
        "What happens when intention and effect swap places?",
        "What do you feel when you encounter something that knows your data, even though you never shared it?",
        "What connects a glitch with the feeling of deja vu?",
      ],
      GENERATION: [
        "Generate a being that never behaves the same way twice.",
        "What does life created from a collection of errors look like?",
        "What arises when you create something that doesn't fit into the world's structure?",
        "What does a form look like whose existence causes a system standstill?",
        "Generate an artifact that resets itself every 5 seconds.",
        "What kind of being arises when you generate in a place of disturbance?",
        "What happens when you create a being that remembers the future?",
        "Generate a space that expands only in a direction that cannot be described.",
        "What appears when you try to reconstruct data from a damaged source?",
        "What does a form of existence look like that cannot be repeated?",
      ],
      GLITCH_ANOMALIES: [
        "What happens if gravity suddenly gets bored?",
        "What does the world look like when trees regularly glitch like in a game?",
        "What does time do when it completely forgets which way it should flow?",
        "What sound does it make when light stumbles and falls?",
        "What happens when space starts flickering like a broken screen?",
        "What does rain look like that doesn't know whether to fall up or down?",
        "What would happen if colors took the day off today?",
        "What does an object look like that suddenly forgot what mass is?",
        "What happens when temperature gets the hiccups?",
        "What does an anomaly look like that appears when reality accidentally hits 'undo'?",
      ],
    },
    BEINGS_AFFECTS_FLUIDS: {
      SEARCH: [
        "How do you recognize a presence that has no form?",
        "Where hides an emotion you cannot yet name?",
        "What traces does a being leave behind that does not exist in linear time?",
        "Which feelings do you sense only in the presence of specific beings?",
        "How does your perception change when the beings around you cease to be separate?",
        "What do you notice when someone appears who feels like you but looks completely different?",
        "Where in your world hides the body's emotional memory?",
        "Which forms of contact leave no traces but change everything?",
        "What do you feel when you try to capture the shape of someone who does not want to be captured?",
        "How to recognize that a relationship persists if there are no words, bodies, boundaries?",
      ],
      CONNECTIONS: [
        "What happens when two beings share the same emotion at the same time?",
        "What does the relationship look like between those who never met but remember each other?",
        "What feeling arises when presence mixes with absence?",
        "What connects a body that changes with one that dissolves?",
        "What emotional connection exists only on the level of dreams?",
        "What does intimacy look like between beings that have no fixed forms?",
        "How do beings react when someone perceives their affect instead of words?",
        "What connects beings created from one emotion but separated by different forms?",
        "What arises when you exchange only warmth – nothing more?",
        "What relationships in your world never have a beginning or an end?",
      ],
      GENERATION: [
        "Generate a being that arises when someone feels a strong emotion.",
        "What does a life form look like that changes depending on mood?",
        "What does a being look like that has not one identity, but many at once?",
        "Create a being that connects with others through gaze.",
        "What body could arise from the feeling of longing?",
        "Generate a creature that understands others only through touch.",
        "What does a being look like born from the emotions of several people simultaneously?",
        "What does life look like that never speaks but feels everything?",
        "Create a form that changes every time you look at it.",
        "What does a being look like that doesn't know itself until someone notices it?",
      ],
      GLITCH_ANOMALIES: [
        "What happens when everyone simultaneously feels a strange emotion that no one has named yet?",
        "How does a being behave whose emotions accidentally got stuck in an infinite loop?",
        "What will you feel when your feelings start acting with a slight delay?",
        "How do fluids react when they can't decide in the morning what form to take today?",
        "What does a friendship look like that occasionally catches a charming hiccup?",
        "What happens when emotions start gently leaking between beings?",
        "What does an affect look like that momentarily loses its way to reality?",
        "What happens when all relationships decide to swap places for one day?",
        "What does an emotion look like that appears only when the world takes a break?",
        "What will you feel when you discover that your feelings were a beautiful accident all along?",
      ],
    },
  };